/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppTop50RouteImport } from './routes/app.top50'
import { Route as AppOutreachRouteImport } from './routes/app.outreach'
import { Route as AppDocsRouteImport } from './routes/app.docs'
import { Route as AppCandidatesRouteImport } from './routes/app.candidates'
import { Route as AppProfileIdRouteImport } from './routes/app.profile.$id'
import { Route as AppDocsSlugRouteImport } from './routes/app.docs.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppTop50Route = AppTop50RouteImport.update({
  id: '/top50',
  path: '/top50',
  getParentRoute: () => AppRoute,
} as any)
const AppOutreachRoute = AppOutreachRouteImport.update({
  id: '/outreach',
  path: '/outreach',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsRoute = AppDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AppRoute,
} as any)
const AppCandidatesRoute = AppCandidatesRouteImport.update({
  id: '/candidates',
  path: '/candidates',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileIdRoute = AppProfileIdRouteImport.update({
  id: '/profile/$id',
  path: '/profile/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppDocsSlugRoute = AppDocsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppDocsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/docs': typeof AppDocsRouteWithChildren
  '/app/outreach': typeof AppOutreachRoute
  '/app/top50': typeof AppTop50Route
  '/app/': typeof AppIndexRoute
  '/app/docs/$slug': typeof AppDocsSlugRoute
  '/app/profile/$id': typeof AppProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/docs': typeof AppDocsRouteWithChildren
  '/app/outreach': typeof AppOutreachRoute
  '/app/top50': typeof AppTop50Route
  '/app': typeof AppIndexRoute
  '/app/docs/$slug': typeof AppDocsSlugRoute
  '/app/profile/$id': typeof AppProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/app/candidates': typeof AppCandidatesRoute
  '/app/docs': typeof AppDocsRouteWithChildren
  '/app/outreach': typeof AppOutreachRoute
  '/app/top50': typeof AppTop50Route
  '/app/': typeof AppIndexRoute
  '/app/docs/$slug': typeof AppDocsSlugRoute
  '/app/profile/$id': typeof AppProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/candidates'
    | '/app/docs'
    | '/app/outreach'
    | '/app/top50'
    | '/app/'
    | '/app/docs/$slug'
    | '/app/profile/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/app/candidates'
    | '/app/docs'
    | '/app/outreach'
    | '/app/top50'
    | '/app'
    | '/app/docs/$slug'
    | '/app/profile/$id'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sitemap.xml'
    | '/app/candidates'
    | '/app/docs'
    | '/app/outreach'
    | '/app/top50'
    | '/app/'
    | '/app/docs/$slug'
    | '/app/profile/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/top50': {
      id: '/app/top50'
      path: '/top50'
      fullPath: '/app/top50'
      preLoaderRoute: typeof AppTop50RouteImport
      parentRoute: typeof AppRoute
    }
    '/app/outreach': {
      id: '/app/outreach'
      path: '/outreach'
      fullPath: '/app/outreach'
      preLoaderRoute: typeof AppOutreachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs': {
      id: '/app/docs'
      path: '/docs'
      fullPath: '/app/docs'
      preLoaderRoute: typeof AppDocsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/candidates': {
      id: '/app/candidates'
      path: '/candidates'
      fullPath: '/app/candidates'
      preLoaderRoute: typeof AppCandidatesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile/$id': {
      id: '/app/profile/$id'
      path: '/profile/$id'
      fullPath: '/app/profile/$id'
      preLoaderRoute: typeof AppProfileIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/docs/$slug': {
      id: '/app/docs/$slug'
      path: '/$slug'
      fullPath: '/app/docs/$slug'
      preLoaderRoute: typeof AppDocsSlugRouteImport
      parentRoute: typeof AppDocsRoute
    }
  }
}

interface AppDocsRouteChildren {
  AppDocsSlugRoute: typeof AppDocsSlugRoute
}

const AppDocsRouteChildren: AppDocsRouteChildren = {
  AppDocsSlugRoute: AppDocsSlugRoute,
}

const AppDocsRouteWithChildren =
  AppDocsRoute._addFileChildren(AppDocsRouteChildren)

interface AppRouteChildren {
  AppCandidatesRoute: typeof AppCandidatesRoute
  AppDocsRoute: typeof AppDocsRouteWithChildren
  AppOutreachRoute: typeof AppOutreachRoute
  AppTop50Route: typeof AppTop50Route
  AppIndexRoute: typeof AppIndexRoute
  AppProfileIdRoute: typeof AppProfileIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCandidatesRoute: AppCandidatesRoute,
  AppDocsRoute: AppDocsRouteWithChildren,
  AppOutreachRoute: AppOutreachRoute,
  AppTop50Route: AppTop50Route,
  AppIndexRoute: AppIndexRoute,
  AppProfileIdRoute: AppProfileIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
